# Header
menu:
  首页: /
  归档: /archives
  相册: /gallery
  关于: /about
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
#sidebar: right
#widgets:
#- category
#- tag
#- tagcloud
#- archive
#- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
#index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
#archive_type: 'monthly'
#show_count: false

# Miscellaneous
google_analytics:
gauges_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:


# Local search
# Dependencies: https://github.com/flashlab/hexo-generator-search
local_search:
  enable: true
  # if auto, trigger search by changing input
  # if manual, trigger search by pressing enter key or search button
  trigger: auto
  # show top n results per article, show all results by setting to -1
  top_n_per_article: 1
  unescape: true