# Menu
menu:
  Home: /
  Archives: /archives
  Gallery: /gallery
  About: /about
  Links: /links
rss: /atom.xml


# Miscellaneous
favicon: /favicon.ico
brand: /images/hexo.svg

# Ocean Video
# Because I put videos in multiple formats on the same path, I just labeled the path here.
ocean:
  overlay: true
  path: /images/ocean/
  brand: /images/hexo-inverted.svg

# Content
excerpt_link: Read More...

# Tags
show_count: false

# Toc
toc: true

# fancybox
fancybox: true

# Gitalk
gitalk:
  enable: false # true
  clientID: # GitHub Application Client ID
  clientSecret: # Client Secret
  repo: # Repository name
  owner: # GitHub ID
  admin: # GitHub ID

# Valine
valine:
  enable: false # true
  el: 'vcomments'
  appId: 
  appKey: 
  notify: false
  verify: true
  avatar: 'mp'
  pageSize: '10'
  placeholder: '请输入...' 

# Katex Support
katex:
  enable: false # true
  allpost:
  copy_tex: