# Menu
menu:
  Home: /
  Archives: /archives
  Gallery: /gallery
  About: /about
rss: /atom.xml


# Miscellaneous
favicon: /favicon.ico
brand: /images/hexo.svg

# Ocean Video
ocean_video_poster: http://source.zhwangart.com/hexo/themes/ocean/video/ocean.png
ocean_video_src: http://source.zhwangart.com/hexo/themes/ocean/video/ocean.mp4
ocean_video_brand: /images/hexo-inverted.svg

# Content
excerpt_link: Read More...
nav_prev_text: Newer posts
nav_next_text: Olde posts
share_text: Share

# fancybox
fancybox: true

# RSS
feed:
  type: atom
  path: atom.xml
  limit: 20
  hub:
  content:
  content_limit: 140
  content_limit_delim: ' '
  order_by: -date

# Local search
search_text: Search
# Dependencies: https://github.com/flashlab/hexo-generator-search
local_search:
  enable: true
  # if auto, trigger search by changing input
  # if manual, trigger search by pressing enter key or search button
  trigger: auto
  # show top n results per article, show all results by setting to -1
  top_n_per_article: 1
  unescape: true